import Head from "next/head";
import { useState } from "react";
import axios from "axios";
import { FcSearch } from "react-icons/fc";
import Image from "next/image";

export default function Home() {
  const [cityName, setCityName] = useState("");
  const [loading, setLoading] = useState(false);
  const [weather, setWeather] = useState({});
  const url = `https://api.openweathermap.org/data/2.5/weather?q=bhiwani&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchApi = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      console.log(response.data);
      setWeather(response.data);
    });
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>Weather Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Image
        src="https://images.unsplash.com/photo-1501186758051-167ca3c0fde8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"
        layout="fill"
        className="object-cover"
      />
      <div className="relative flex justify-between items-center m-[20%] ml-[40%]">
        <form >
          <input type="text" className="w-96 h-16" placeholder="Enter City" />
          <button onClick={fetchApi}><FcSearch size={30} className='w-16 h-14' /></button>
        </form>
      </div>
    </div>
  );
}
