import Head from "next/head";
import { useState } from "react";
import axios from "axios";
import { FcSearch } from "react-icons/fc";
import Image from "next/image";
import Weather from "../Components/Weather";

export default function Home() {
  const [cityName, setCityName] = useState("");
  const [weather, setWeather] = useState({});
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${cityName}&units=metric&lang={hi}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchApi = (e) => {
    e.preventDefault();
    axios.get(url).then((response) => {
      // console.log(response.data);
      setWeather(response.data);
    });
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>Weather Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
      <Image
        src="https://images.unsplash.com/photo-1501186758051-167ca3c0fde8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"
        layout="fill"
        className="object-cover w-full h-fit"
        />
      <div className="relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10 sm:w-[390px]">
        <form onSubmit={fetchApi} className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl" >
          <input type="text" value={cityName} onChange={e=>setCityName(e.target.value)} className="bg-transparent border-none text-white focus:outline-none text-2xl"  placeholder="Enter City" />

          <button onClick={fetchApi}><FcSearch size={30} className='w-16 h-14' /></button>
        </form>
      </div>
      {weather.main && <Weather weatherData={weather} />}
        </div>

    
  );
}
